export const APP_DEFAULT_TEXT_COLOR_RGB_STRING = '197, 197, 198';
export const APP_PRIMARY_COLOR_RGB_STRING = '16, 185, 129';
export const APP_ALTERNATIVE_COLOR_RGB_STRING = '134, 234, 175';
export const APP_DANGER_COLOR_RGB_STRING = '251,93,71';
export const APP_SUCCESS_COLOR_RGB_STRING = '2,191,77';

export const APP_DEFAULT_TEXT_COLOR = `rgba(${APP_DEFAULT_TEXT_COLOR_RGB_STRING}, 1)`;
export const APP_PRIMARY_COLOR = `rgba(${APP_PRIMARY_COLOR_RGB_STRING},1)`;
export const APP_ALTERNATIVE_COLOR = `rgba(${APP_ALTERNATIVE_COLOR_RGB_STRING},1)`;
export const APP_DANGER_COLOR = `rgba(${APP_DANGER_COLOR_RGB_STRING},1)`;
export const APP_SUCCESS_COLOR = `rgba(${APP_SUCCESS_COLOR_RGB_STRING},1)`;
